namespace: monitoring

resources:
- ./namespace.yaml
- ./manifests/thanos-query-deployment.yaml
- ./manifests/thanos-query-service.yaml
- ./manifests/thanos-query-serviceAccount.yaml
- ./manifests/thanos-receive-ingestor-default-service.yaml
- ./manifests/thanos-receive-ingestor-default-statefulSet.yaml
- ./manifests/thanos-receive-ingestor-serviceAccount.yaml
- ./manifests/thanos-receive-router-configmap.yaml
- ./manifests/thanos-receive-router-deployment.yaml
- ./manifests/thanos-receive-router-service.yaml
- ./manifests/thanos-receive-router-serviceAccount.yaml
- ./ingress-query.yaml
- ./ingress-receive-router.yaml