apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
 name: kuadrant-addon
 namespace: kind-mgc-workload-1
spec:
 installNamespace: open-cluster-management-agent-addon
 configs:
  - resource: configmaps 
    name: install-config
    namespace: kind-mgc-workload-1
 
 