apiVersion: kuadrant.io/v1alpha2
kind: DNSRecord
metadata:
  name: dnsrecord-geo
spec:
  providerRef:
    name: managedzone-sample
    kind: ManagedZone
  endpoints:
    - dnsName: dnsrecord-geo.mn.hcpapps.net
      recordTTL: 60
      recordType: CNAME
      setIdentifier: Default
      providerSpecific:
        - name: "aws/geolocation-country-code"
          value: "*"
      labels:
        id: Default
      targets:
        - dnsrecord-geo.na.mn.hcpapps.net
    - dnsName: dnsrecord-geo.mn.hcpapps.net
      recordTTL: 60
      recordType: CNAME
      setIdentifier: NA
      providerSpecific:
        - name: "aws/geolocation-continent-code"
          value: "NA"
      labels:
        id: NA
      targets:
        - dnsrecord-geo.na.mn.hcpapps.net
    - dnsName: dnsrecord-geo.na.mn.hcpapps.net
      recordTTL: 60
      recordType: A
      setIdentifier: 50.16.23.1
      providerSpecific:
        - name: "weight"
          value: "60"
      labels:
        id: 50.16.23.1
      targets:
        - 50.16.23.1
    - dnsName: dnsrecord-geo.na.mn.hcpapps.net
      recordTTL: 60
      recordType: A
      setIdentifier: 50.16.23.2
      providerSpecific:
        - name: "weight"
          value: "60"
      labels:
        id: 50.16.23.2
      targets:
        - 50.16.23.2
