apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mctc
webhooks:
  - name: "mctc.ingress.dev"
    clientConfig:
      caBundle: ""
      url: https://webhook.172.32.0.2.nip.io/ingress
    timeoutSeconds: 5
    sideEffects: NoneOnDryRun
    admissionReviewVersions: ["v1"]
    matchPolicy: Exact
    failurePolicy: Fail
    rules:
      - apiGroups:
          - "networking.k8s.io"
        apiVersions: ["v1"]
        resources:
          - "ingresses"
          - "ingresses/status"
        scope: "*"
        operations:
          - CREATE
          - UPDATE
