apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: gateway-clusters
spec:
  clusterSelector:
    labelSelector:
      matchLabels:
        ingress-cluster: "true"
    selectorType: LabelSelector