apiVersion: kuadrant.io/v1alpha1
kind: ManagedZone
metadata:
  name: dev-mz-aws
spec:
  id: DUMMY_ID
  domainName: DUMMY_DOMAIN_NAME
  description: "Dev Managed Zone"
  dnsProviderSecretRef:
    name: mgc-aws-credentials
    namespace: multi-cluster-gateways

