apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: echo-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: mctc-control-plane
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-echo-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Kuadrant/multicluster-gateway-controller.git'
        targetRevision: HEAD
        path: samples/echo-service
      destination:
        server: '{{url}}'
        namespace: echo-app
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true